- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: ram-keypair
    instance_type: t2.micro
    security_group: ELB
    image: ami-0c284906fe7cbbff0
    region: us-east-2

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-0e4f7f18e7296ffa3
         assign_public_ip: yes
      register: ec2

    - local_action:
        module: ec2_elb_lb
        name: "test-vpc"
        scheme: internal
        state: present
        instance_ids:
          - i-0c4174d8f42a98b5e
        purge_instance_ids: true
        subnets:
          - subnet-0e4f7f18e7296ffa3
        listeners:
          - protocol: http # options are http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80

    
