---
- name:                    Create a new Demo EC2 instance
  hosts:                   localhost
  gather_facts:            False

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-52b6d518
         assign_public_ip: yes
         aws_access_key: "{{ AWS_ACCESS_KEY }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: ec2
