---

  - name:       Make sure all groups are present
    group:
      name:     "{{ item.name }}"
      gid:      "{{ item.gid | default(omit) }}"
      state:    present
    with_items: "{{ group_list }}"
