---

  - name:     Crontab entry to logrotate every hour
    cron:
      name:   Run logrotate every hour daily-logrotate
      minute: "0"
      job:    "/usr/local/bin/crontab /etc/cron.daily/logrotate"
      state:  present
      user:   root
