---

  - include_vars: ../../../../inventories/"{{ environment }}"/group_vars/groups.yml

  - name:       Creating Groups
    group:      name="{{item.name}}" gid="{{item.gid}}"
    when:       ansible_distribution == "RedHat"
    with_items:
          - { name: "{{ groups }}", gid: "{{ gid }}" }
