---
  - hosts:         common
    remote_user:   jenkins
    become:        yes
    become_method: sudo
    gather_facts:  yes
    vars_files:
      - ../../inventories/staging/group_vars/users.yml
      - ../../inventories/staging/group_vars/groups.yml
    roles:
      - role:      users
      - role:      groups
      - role:      ssh
      - role:      packages
      - role:      limits
      - role:      firewall
      - role:      cron

