---
- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: suman
    instance_type: t2.micro
    security_group: suman123
    image: ami-03291866
    region: us-east-2

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-535a5d1e
         assign_public_ip: yes
      register: ec2
