---
- name:                    Create a new Demo EC2 instance
  hosts:                   localhost
  gather_facts:            False

  vars:
      region:              us-east-1b
      instance_type:       t2.micro
      ami:                 ami-6871a115 # RHEL
      keypair:             ansible # pem file name
      sg_group:            SG for EBL
      count_value:         1
      ec2_state:           present

  tasks:

    - name:                Create an ec2 instance
      ec2:
         key_name:         "{{ keypair }}"
         group:            "{{ sg_group }}"  # security group name
         instance_type:    "{{ instance_type}}"
         image:            "{{ ami }}"
         wait:             true
         region:           "{{ region }}"
         count:            "{{ count_value }}"  # default
         count_tag:
            Name:          Demo
         instance_tags:
            Name:          apss-test01
         vpc_subnet_id:    subnet-52b6d518
         assign_public_ip: yes
         state:            "{{ ec2_state }}"
      register:            ec2



