- name:                    Create Security Group and EC2 instance
  hosts:                   localhost
  gather_facts:            False

tasks:
  - name: Create security group
    ec2_group:
      name: Custome_sg_group1
      description: security group creation
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp  # ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp  # http
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp  # https
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0


    - name:                Create an ec2 instance
      ec2:
         key_name:         "{{ keypair }}"
         group:            "{{ sg_group }}"  # security group name
         instance_type:    "{{ instance_type}}"
         image:            "{{ ami }}"
         wait:             true
         region:           "{{ region }}"
         count:            "{{ count_value }}"  # default
         count_tag:
            Name:          Demo
         instance_tags:
            Name:          apss-test01
         vpc_subnet_id:    "{{ vpc_subnet_id }}"
         assign_public_ip: yes
         state:            "{{ ec2_state }}"
      register:            ec2
