pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                ansible-playbook -e "bucket=apss1-web-test1 region=us-east-2 vpc_id=vpc-b99ad2d1 sg_name=pradeepsg" aws-ansible/playbooks/ec2/ec2.yml
            }
        }

    }
}
